#!/usr/bin/env bash
# This script is looping from 0 to 10 and displaying "bad luck" if it's 4 and displays "good luck" if it's 8
i=0
while ((i<10))
do
((i++))
if [ $i -eq 4 ]
then
echo "bad luck"
elif [ $i -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
done
