#!/usr/bin/env bash
# this script prints to infinity and beyond and stop the loop using kill command
prog_pid=()
readarray -t prog_pid < <(pgrep -la -x "bash.*" | grep '4-to_infinity_and_beyond' | cut -d ' ' -f 1)
for ((i=0; i < "${#prog_pid[0]}"; i++)) do
kill -s SIGTERM "${prog_pid[i]}"
done
